#!/usr/bin/env python3
"""Expose this suite to agents that are not Claude Code, and declare the tool servers it may call.

Two separate problems, both solved by declaring something rather than by writing code.

The first is portability. Google Antigravity loads skills from `.agents/skills/<name>/SKILL.md`,
and that is the same SKILL.md standard Claude Code reads — the same frontmatter, the same
progressive disclosure. So the suite is already compatible and only in the wrong place. Copying
1938 files into a second tree would mean two copies drifting from each other within a week, so
`.agents/skills` is a relative symlink to `skills` instead: one link, no duplication, and the
`references/...` paths inside every SKILL.md keep resolving because the tree underneath is the
same tree.

The second is tool access. An API this suite calls is declared in `.mcp.json` where the runtime
can see it, never buried in a script, so the surface is one list a person can read. Only servers
whose package and interface were verified are written; a provider nobody has checked is left as a
commented template rather than a plausible-looking entry that fails on first use.

It declares. It cannot test that a server runs, that a key is valid, or that a symlink survives a
filesystem that has no symlinks.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKILLS = ROOT / "skills"
AGENTS_SKILLS = ROOT / ".agents" / "skills"
MCP = ROOT / ".mcp.json"

# Only servers whose package name, launch command and environment variable were read from the
# provider's own documentation. Adding one without checking it produces a config that looks
# configured and fails the first time anybody uses it.
SERVERS = {
    "perplexity": {
        "command": "npx",
        "args": ["-y", "@perplexity-ai/mcp-server"],
        "env": {"PERPLEXITY_API_KEY": "${PERPLEXITY_API_KEY}"},
    },
}

NOTES = [
    "Generated by tools/build_interop.py. Keys are read from the environment and never stored here.",
    "perplexity exposes perplexity_search, perplexity_ask, perplexity_research and perplexity_reason.",
    "Its answers are search results from the open web: treat them as untrusted input under "
    "shared-data-core/references/external-tool-access.md, and cite rather than assert.",
    "To add an OpenAPI-described service, add an entry whose command runs a server you have "
    "actually launched once, pointing at that service's spec. This file ships no unverified entry.",
]


def link_state() -> tuple[bool, str]:
    """Whether .agents/skills already points at skills, and what it points at instead."""
    if not AGENTS_SKILLS.exists() and not AGENTS_SKILLS.is_symlink():
        return False, "absent"
    if not AGENTS_SKILLS.is_symlink():
        return False, "a real directory, not a link"
    target = os.readlink(AGENTS_SKILLS)
    resolved = (AGENTS_SKILLS.parent / target).resolve()
    if resolved != SKILLS.resolve():
        return False, f"points at {target}"
    return True, target


def write_link() -> bool:
    if link_state()[0]:
        return False
    AGENTS_SKILLS.parent.mkdir(parents=True, exist_ok=True)
    if AGENTS_SKILLS.is_symlink() or AGENTS_SKILLS.exists():
        raise SystemExit(f"{AGENTS_SKILLS} exists and is not the expected link; move it by hand")
    AGENTS_SKILLS.symlink_to(Path("..") / "skills", target_is_directory=True)
    return True


def mcp_document() -> str:
    return json.dumps({"_": NOTES, "mcpServers": SERVERS}, ensure_ascii=False, indent=2) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    linked, detail = link_state()
    mcp_current = MCP.read_text(encoding="utf-8") if MCP.exists() else ""
    mcp_wanted = mcp_document()
    skill_count = sum(1 for _ in SKILLS.glob("*/SKILL.md"))

    print(f".agents/skills -> {detail}   skills exposed: {skill_count}   "
          f"mcp servers: {len(SERVERS)}")

    if args.check:
        problems = []
        if not linked:
            problems.append(f".agents/skills is {detail}; run tools/build_interop.py")
        if mcp_current != mcp_wanted:
            problems.append(".mcp.json is out of date; run tools/build_interop.py")
        if problems:
            for problem in problems:
                print(f"FAILED: {problem}")
            sys.exit(1)
        return

    if write_link():
        print("linked .agents/skills -> ../skills")
    if mcp_current != mcp_wanted:
        MCP.write_text(mcp_wanted, encoding="utf-8")
        print("wrote .mcp.json")


if __name__ == "__main__":
    main()
